export interface ExerciseSeed {
  id: string;
  name: string;
  pattern: string;
  equipment: string[];
  cues: string[];
  substitutions: Array<{ id: string; reason: string }>;
  painSafeFor: string[];
}

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  {
    id: 'back-squat',
    name: 'Back Squat',
    pattern: 'squat',
    equipment: ['barbell', 'rack'],
    cues: ['Brace hard', 'Knees track toes', 'Depth with neutral spine'],
    substitutions: [{ id: 'goblet-squat', reason: 'Shoulder/low-back friendly' }],
    painSafeFor: ['shoulder'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    pattern: 'squat',
    equipment: ['barbell', 'rack'],
    cues: ['Elbows high', 'Upright torso'],
    substitutions: [{ id: 'goblet-squat', reason: 'Wrist/shoulder limitation' }],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    pattern: 'squat',
    equipment: ['dumbbell'],
    cues: ['Sit between hips', 'Keep chest up'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    pattern: 'hinge',
    equipment: ['barbell'],
    cues: ['Hinge at hips', 'Soft knee', 'Bar close to legs'],
    substitutions: [{ id: 'hip-thrust', reason: 'Low-back sensitivity' }],
    painSafeFor: ['shoulder'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    pattern: 'hinge',
    equipment: ['barbell', 'bench'],
    cues: ['Chin tucked', 'Drive through heels'],
    substitutions: [],
    painSafeFor: ['lowBack', 'shoulder'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    pattern: 'squat',
    equipment: ['dumbbell', 'bench'],
    cues: ['Torso slight forward', 'Front knee stable'],
    substitutions: [{ id: 'goblet-squat', reason: 'Balance or knee issue' }],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'bench-press',
    name: 'Bench Press',
    pattern: 'push',
    equipment: ['barbell', 'bench'],
    cues: ['Feet planted', 'Bar path to lower chest'],
    substitutions: [{ id: 'overhead-press', reason: 'Shoulder pain on horizontal press' }],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    pattern: 'push',
    equipment: ['barbell'],
    cues: ['Ribs down', 'Head through at lockout'],
    substitutions: [{ id: 'face-pull', reason: 'Shoulder impingement' }],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    pattern: 'pull',
    equipment: ['barbell'],
    cues: ['Hinge stable', 'Pull to hip crease'],
    substitutions: [{ id: 'pull-up', reason: 'Low-back fatigue' }],
    painSafeFor: ['shoulder'],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    pattern: 'pull',
    equipment: ['pull-up-bar'],
    cues: ['Full hang', 'Chest to bar'],
    substitutions: [{ id: 'barbell-row', reason: 'Grip or elbow issue' }],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    pattern: 'pull',
    equipment: ['cable'],
    cues: ['External rotation', 'Pull to forehead'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    pattern: 'calf',
    equipment: ['machine'],
    cues: ['Pause at top', 'Controlled descent'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'plank',
    name: 'Plank',
    pattern: 'core',
    equipment: ['bodyweight'],
    cues: ['Ribs down', 'Glutes engaged'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    pattern: 'core',
    equipment: ['cable', 'band'],
    cues: ['Resist rotation', 'Exhale on press'],
    substitutions: [],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    pattern: 'skill',
    equipment: ['bodyweight'],
    cues: ['Posterior pelvic tilt', 'Breathe into stretch'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'ankle-mobility',
    name: 'Ankle Mobility Drill',
    pattern: 'skill',
    equipment: ['bodyweight'],
    cues: ['Knee over toe', 'Heel down'],
    substitutions: [],
    painSafeFor: ['shoulder', 'lowBack'],
  },
  {
    id: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    pattern: 'skill',
    equipment: ['bodyweight'],
    cues: ['Hinge with flat back', 'No bounce'],
    substitutions: [],
    painSafeFor: ['lowBack'],
  },
  {
    id: 'shoulder-dislocates',
    name: 'Shoulder Dislocates',
    pattern: 'skill',
    equipment: ['band'],
    cues: ['Wide grip', 'Slow arc'],
    substitutions: [],
    painSafeFor: ['lowBack'],
  },
];
